# Generated by Django 3.2.4 on 2022-07-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['title', 'description'], name='videos_vide_title_67b4f6_idx'),
        ),
    ]
